import { Inspiration, COLOR_OPTIONS } from '../types'

const getRandomColor = () => COLOR_OPTIONS[Math.floor(Math.random() * COLOR_OPTIONS.length)]

export const demoInspirations: Inspiration[] = [
  {
    id: 'demo-1',
    content: '今天突然想到一个新的应用创意：一个可以记录和分析梦境的应用，用户可以记录自己的梦境，系统会分析梦境的主题和情感，帮助用户了解自己的潜意识。',
    tags: ['创意', '应用', '梦境', '分析'],
    emotion: 'excited',
    color: getRandomColor(),
    createdAt: new Date('2026-04-15T10:30:00'),
    updatedAt: new Date('2026-04-15T10:30:00'),
    supplements: [
      {
        id: 'demo-sup-1',
        content: '可以添加AI分析功能，识别梦境中的常见元素和象征意义',
        type: 'thought',
        attachments: [],
        createdAt: new Date('2026-04-15T10:45:00'),
      },
    ],
    attachments: [],
  },
  {
    id: 'demo-2',
    content: '在阅读关于冥想的文章时，想到一个结合冥想和音乐的应用，用户可以根据自己的情绪选择适合的冥想音乐，系统会根据用户的反馈调整音乐推荐。',
    tags: ['冥想', '音乐', '情绪', '应用'],
    emotion: 'calm',
    color: getRandomColor(),
    createdAt: new Date('2026-04-14T14:20:00'),
    updatedAt: new Date('2026-04-14T14:20:00'),
    supplements: [],
    attachments: [],
  },
  {
    id: 'demo-3',
    content: '在咖啡店看到人们使用笔记本电脑工作，想到一个专注于提升工作效率的应用，它可以记录用户的工作习惯，分析哪些时间最适合专注工作，哪些任务需要更多时间。',
    tags: ['效率', '工作', '分析', '应用'],
    emotion: 'curious',
    color: getRandomColor(),
    createdAt: new Date('2026-04-13T09:15:00'),
    updatedAt: new Date('2026-04-13T09:15:00'),
    supplements: [
      {
        id: 'demo-sup-2',
        content: '可以添加番茄工作法功能，帮助用户保持专注',
        type: 'note',
        attachments: [],
        createdAt: new Date('2026-04-13T10:00:00'),
      },
    ],
    attachments: [],
  },
  {
    id: 'demo-4',
    content: '在散步时想到，现在的社交媒体太注重展示完美的一面，应该创建一个更真实、更私密的社交平台，让用户可以分享自己的不完美和真实感受。',
    tags: ['社交', '真实', '隐私', '创意'],
    emotion: 'anxious',
    color: getRandomColor(),
    createdAt: new Date('2026-04-12T16:45:00'),
    updatedAt: new Date('2026-04-12T16:45:00'),
    supplements: [],
    attachments: [],
  },
  {
    id: 'demo-5',
    content: '在学习编程时，想到一个帮助初学者学习编程的应用，它可以根据用户的学习进度和兴趣推荐适合的学习资源，提供个性化的学习路径。',
    tags: ['编程', '学习', '教育', '应用'],
    emotion: 'neutral',
    color: getRandomColor(),
    createdAt: new Date('2026-04-11T11:30:00'),
    updatedAt: new Date('2026-04-11T11:30:00'),
    supplements: [
      {
        id: 'demo-sup-3',
        content: '可以添加代码实践功能，让用户在应用中直接编写和运行代码',
        type: 'progress',
        attachments: [],
        createdAt: new Date('2026-04-11T12:00:00'),
      },
    ],
    attachments: [],
  },
  {
    id: 'demo-6',
    content: '在旅行时，想到一个基于地理位置的旅行灵感应用，用户可以看到附近其他人分享的旅行灵感和推荐地点，也可以分享自己的发现。',
    tags: ['旅行', '灵感', '地理位置', '分享'],
    emotion: 'excited',
    color: getRandomColor(),
    createdAt: new Date('2026-04-10T15:20:00'),
    updatedAt: new Date('2026-04-10T15:20:00'),
    supplements: [],
    attachments: [],
  },
  {
    id: 'demo-7',
    content: '在健身房锻炼时，想到一个结合运动和游戏化的应用，用户可以通过完成运动目标解锁游戏内容，增加运动的趣味性和动力。',
    tags: ['运动', '游戏化', '健康', '应用'],
    emotion: 'excited',
    color: getRandomColor(),
    createdAt: new Date('2026-04-09T08:15:00'),
    updatedAt: new Date('2026-04-09T08:15:00'),
    supplements: [
      {
        id: 'demo-sup-4',
        content: '可以添加社交功能，让用户与朋友一起完成运动挑战',
        type: 'thought',
        attachments: [],
        createdAt: new Date('2026-04-09T09:00:00'),
      },
    ],
    attachments: [],
  },
  {
    id: 'demo-8',
    content: '在烹饪时，想到一个智能食谱应用，它可以根据用户现有的食材推荐食谱，减少食物浪费，同时提供个性化的饮食建议。',
    tags: ['烹饪', '食谱', '智能', '环保'],
    emotion: 'curious',
    color: getRandomColor(),
    createdAt: new Date('2026-04-08T18:30:00'),
    updatedAt: new Date('2026-04-08T18:30:00'),
    supplements: [],
    attachments: [],
  },
]
